--시퀀스는 각자 생성해주세요~!~
--MEMBER
CREATE TABLE MEMBER (	
	NO NUMBER NOT NULL, 
	ID VARCHAR2(20) NOT NULL, 
	PASSWORD VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(50) NOT NULL, 
	CODE VARCHAR2(50) NOT NULL, 
	SUBJECT VARCHAR2(50),
	TELL VARCHAR2(15) NOT NULL, 
	EMAIL VARCHAR2(100), 
	REGDATE DATE NOT NULL
);

select * from member;
delete from member where no = 32;
commit;

INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'dd','1234','최재영','S0004','sixth','000-0000-000','hong@gmail.com',SYSDATE);
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'sd','1234','윤재석','S0002','second','000-0000-000','hong@gmail.com',SYSDATE);
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'tr','1234','몽구스','M0001','third','000-0000-000','test@gmail.com',SYSDATE);

--ATTEND
 CREATE TABLE ATTEND (	
	NO NUMBER NOT NULL, 
	CODE VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(50) NOT NULL, 
	SUBJECT VARCHAR2(50) NOT NULL, 
	ATTENDDATE DATE NOT NULL, 
	ATTENDTIME DATE NOT NULL, 
	LEAVETIME DATE, 
	STATE VARCHAR2(100) NOT NULL
);


--BOARD
CREATE TABLE BOARD 
   (	NO NUMBER NOT NULL, 
	TITLE VARCHAR2(100) NOT NULL, 
	CATEGORY VARCHAR2(100), 
	CODE VARCHAR2(100) NOT NULL, 
	ID VARCHAR2(100) NOT NULL, 
	REGDATE DATE NOT NULL, 
	REGROUP NUMBER, 
	RELEVEL NUMBER, 
	RESTEP NUMBER, 
	HIT NUMBER NOT NULL, 
	CONTENTS VARCHAR2(1000)
   ) ;
   
   select * from lecture;
   
INSERT INTO BOARD VALUES (SEQ_BOARD.NEXTVAL,'question_test','question','S0001','test',to_date('22/04/11 17:19:05','RR/MM/DD HH24:MI:SS'),1,1,1,0,'내용입니다.');
INSERT INTO BOARD VALUES (SEQ_BOARD.NEXTVAL,'notice_test','notice','S0001','test',to_date('22/04/08 21:10:47','RR/MM/DD HH24:MI:SS'),1,1,1,9,'내용입니다.');
INSERT INTO BOARD VALUES (SEQ_BOARD.NEXTVAL,'etc_test','etc','S0001','test',to_date('22/04/11 17:40:19','RR/MM/DD HH24:MI:SS'),5,1,1,3,'내용입니다.');

--LECTURE
CREATE TABLE LECTURE 
   (	NO NUMBER NOT NULL, 
	SUBJECT VARCHAR2(100) NOT NULL, 
	TEACHER VARCHAR2(100) NOT NULL, 
	SELECTDATE DATE NOT NULL, 
	CONTENTS VARCHAR2(1000)
   );
    SELECT * FROM LECTURE;
   SELECT * FROM LECTURE WHERE SUBJECT = 'sixth' AND SELECTDATE = TO_DATE('2022-04-22', 'yyyy-mm-dd');
   
   INSERT INTO LECTURE VALUES(SEQ_LECTURE.NEXTVAL, 'sixth','홍길동',trunc(sysdate,'dd'),'일정내용입력');
   INSERT INTO LECTURE VALUES(SEQ_LECTURE.NEXTVAL, 'sixth','몽구스',trunc(sysdate,'dd'),'일정내용입력');
   delete from lecture WHERE NO = 1;
   
   select TO_DATE(TO_CHAR(SYSDATE, 'YYYYMMDD')) - TO_DATE('20220420') from dual;
   TO_CHAR(SYSDATE, 'YYYYMMDD');
   TO_CHAR(TRUNC(SYSDATE,'mm') ,'yyyy/mm/dd');
   commit;